"""rename address

Revision ID: 2263e069a56c
Revises: edc9cfb86f5d
Create Date: 2025-03-27 11:42:47.587765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2263e069a56c'
down_revision = 'edc9cfb86f5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments','address', new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments','location',new_column_name='address')
    # ### end Alembic commands ###
